### RANDOM.RAND

In [3]:
import numpy as np
# Gera números aleatórios de distribuição uniforme entre 0 e 1
# Gera uma matriz 2x3 de números aleatórios uniformemente distribuídos entre 0 e 1
arr = np.random.rand(2,3)
arr

array([[0.73976805, 0.42254802, 0.23065599],
       [0.20600941, 0.587985  , 0.56972454]])

### RANDOM.RANDINT

In [6]:
# Gera números inteiros aleatórios dentro de um intervalo especificado.
# Gera um número inteiro aleatório entre 0 e 9
num = np.random.randint(0, 10)
# Gera uma matriz 2x3 de números inteiros aleatórios entre 0 e 100
arr = np.random.randint(0, 100, size=(2, 3))
arr

array([[22,  0, 37],
       [66,  8, 62]])

### RANDOM.RANDN

In [24]:
# Gera números aleatórios com distribuição normal padrão
# Gera uma matriz 2x3 de números aleatórios com distribuição normal
arr = np.random.randn(2, 3)
arr

array([[ 1.57921282,  0.76743473, -0.46947439],
       [ 0.54256004, -0.46341769, -0.46572975]])

### RANDOM.CHOICE

In [26]:
# Escolhe aleatoriamente 3 elementos da lista
# Escolhe aleatoriamente elementos de uma lista, com ou sem reposição.
arr = np.random.choice([1, 2, 3, 4, 5], size=3)
arr

array([4, 2, 5])

### RANDOM.SEED

In [28]:
np.random.seed(42)  # Define a semente
arr = np.random.rand(2, 3)  # Gera números aleatórios com a mesma semente
arr

array([[0.37454012, 0.95071431, 0.73199394],
       [0.59865848, 0.15601864, 0.15599452]])